name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        opamwithtest: [true, false]
        recursive: ["", --recursive]
        exclude:
          - opamwithtest: false
            recursive: ""
    steps:
    - uses: actions/checkout@v1
    - name: Build the whole xs-toolstack
      run: bash tools/travis.sh
