name: xs-toolstack build

on:
  push:
    branches:
      - master
    tags:
      - '*.0'
  pull_request:
    branches:
      - master
  schedule:
    # run daily
    - cron: '41 3 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [4.08, 4.09]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.3
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
        env:
          OCAML_VERSION: ${{ matrix.ocaml-version }}
        continue-on-error: ${{ matrix.ocaml-version == 4.09 }}
