name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        OPAMWITHTEST: [true, false]
        RECURSIVE: ["", --recursive]
        exclude:
          - OPAMWITHTEST: false
            RECURSIVE: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
