name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env: [OPAMWITHTEST: false,
              OPAMWITHTEST: true,
              { OPAMWITHTEST: true,
                RECURSIVE: --recursive
              }
             ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the whole xs-toolstack
        run: bash tools/travis.sh
